Section 1
ArturMay/Homework-4 pull request #1
Opened 2021-07-13 09:54 UTC by ArturMay

@RuslanFahrenheit, HTML and CSS for the first section have been added

2021-07-13 14:01 UTC, RuslanFahrenheit requested changes
1. Why do you have two identical commits: "Added HTML and CSS for the first section"? First commit is about adding configuration for processor. Describe your commits carefully.
Also read [Как писать сообщения коммитов в Git](https://medium.com/grisme/%D0%BA%D0%B0%D0%BA-%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%BE%D0%B2-%D0%B2-git-9ed19ebc5ebf).
2. I don't see typography styles.
3. Don't write styles in one file. Read:
- https://qna.habr.com/q/741337
- http://prgssr.ru/development/estetichnyj-sass-chast-1-arhitektura-i-organizaciya.html#heading-section

2021-07-13 14:01 UTC, RuslanFahrenheit commented on scss/style.scss
> +
Redundant empty line.

2021-07-13 14:01 UTC, RuslanFahrenheit commented on scss/style.scss
> +    padding:0 20px;
Code style. Check formatting all over the file.

2021-07-13 14:01 UTC, RuslanFahrenheit commented on scss/style.scss
> +    // border: 1px solid rgb(69, 151, 80);
Remove commented code.

2021-07-13 14:01 UTC, RuslanFahrenheit commented on scss/style.scss
> +}
Add a blank line at the end.

2021-07-13 14:01 UTC, RuslanFahrenheit commented on index.html
> +    <header>
An entire section is wrapped in `<header>`. Why? Is this really header?

2021-07-13 14:01 UTC, RuslanFahrenheit commented on index.html
> +      <div class="visual-box">
What is the meaning of 'visual-box' class name? I think there are more semantically correct options.
E.g. https://www.google.com/search?client=firefox-b-d&q=hero+section

2021-07-13 14:01 UTC, RuslanFahrenheit commented on index.html
> +            </div>
It's a bad idea to use text as a logo. It should always looks the same. Imagine fonts not loading. Always use image as a logo.
E.g. https://www.adidas.com/us 
They don't type 'ADIDAS'. It's an image.

2021-07-13 14:01 UTC, RuslanFahrenheit commented on index.html
>  </html>
Add blank line.

2021-07-13 14:01 UTC, RuslanFahrenheit commented on index.html
> +            <span>Show More</span>
What is the purpose of `span` inside the link tag?

2021-07-13 14:01 UTC, RuslanFahrenheit commented on index.html
> +          <h1>BLACK<span class="highlighter">&</span>WHITE</h1>
I suppose "highlighting" is more about making something stand out with color.
Not critical, but think about more semantically correct name.

2021-07-14 20:34 UTC, ArturMay commented on index.html
> +            <span>Show More</span>
For making bigger font-size to the symbol "&"

2021-07-14 20:45 UTC, ArturMay commented on scss/style.scss
> +    padding:0 20px;
+

2021-07-14 20:45 UTC, ArturMay commented on scss/style.scss
> +    // border: 1px solid rgb(69, 151, 80);
I will remove it in the end, it helps me

2021-07-14 20:46 UTC, ArturMay commented on scss/style.scss
> +}
done

2021-07-14 21:36 UTC, ArturMay commented on index.html
> +    <header>
<main> has been added. Now <header> contains logo and menu (naviagtion) only

2021-07-14 21:39 UTC, ArturMay commented on index.html
> +      <div class="visual-box">
'visual box has been changed to 'hero-section'

2021-07-14 21:43 UTC, ArturMay commented on index.html
> +            </div>
Text in the logo has been changed to image

2021-07-14 21:44 UTC, ArturMay commented on index.html
>  </html>
done. it was the hardest one :)

2021-07-14 21:47 UTC, ArturMay commented on scss/style.scss
> +
done

2021-07-15 21:29 UTC, ArturMay commented on index.html
> +          <h1>BLACK<span class="highlighter">&</span>WHITE</h1>
Changed to "enlarger"

2021-07-17 15:30 UTC, RuslanFahrenheit commented
TODO:
- style.scss - only imports here;
- code style;
- remove %button extender;
- add class to `<header>`.

2021-07-22 19:45 UTC, merged